<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'JanDrabek\\MailPanel\\' => array($vendorDir . '/jandrabek/nette-mailpanel/src'),
);
