<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Nextras\\TracyQueryPanel\\Handlers\\' => array($vendorDir . '/nextras/tracy-query-panel/src/handlers'),
    'Nextras\\TracyQueryPanel\\' => array($vendorDir . '/nextras/tracy-query-panel/src/TracyQueryPanel'),
);
